// Generated by website-builder from design-repo/tokens/ (source: https://brand.ai/). Tailwind v3. Do not hand-edit; re-run the scrape.
// Values are measured from computed styles; names are heuristic. Nothing here overrides Tailwind's default scales.
// Breakpoints: bp-<px> = min-width, bp-max-<px> = max-width (measured from the site's CSS media queries).
export default {
  corePlugins: { preflight: false }, // the site's own CSS is the reset
  "content": [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx,html}"
  ],
  "theme": {
    "extend": {
      "colors": {
        "neutral-01": "rgb(27,27,27)",
        "neutral-02": "rgb(247,245,242)",
        "neutral-03": "rgb(255,255,255)",
        "neutral-04": "rgb(140,135,125)",
        "neutral-05": "rgb(187,186,179)",
        "neutral-06": "rgb(20,20,20)",
        "neutral-07": "rgb(210,210,210)",
        "neutral-08": "rgb(10,10,10)",
        "neutral-09": "rgb(235,233,230)",
        "green-01": "rgb(0,128,0)",
        "neutral-10": "rgba(215,215,215,0.5)",
        "neutral-11": "rgba(255,255,255,0.15)",
        "orange-01": "rgb(240,238,234)",
        "green-02": "rgb(41,205,96)",
        "neutral-12": "rgba(255,255,255,0.4)",
        "neutral-13": "rgb(38,38,38)",
        "neutral-14": "rgba(0,0,0,0.05)",
        "neutral-15": "rgb(0,0,0)",
        "neutral-16": "rgba(255,255,255,0.1)",
        "neutral-17": "rgba(247,245,242,0.8)",
        "neutral-18": "rgb(168,163,159)",
        "surface-default": "rgb(27,27,27)",
        "surface-alt": "rgb(247,245,242)",
        "surface-inverse": "rgb(247,245,242)",
        "surface-accent": "rgb(0,128,0)",
        "text-primary": "rgb(27,27,27)",
        "text-inverse": "rgb(247,245,242)",
        "text-accent": "rgb(41,205,96)",
        "border-default": "rgb(210,210,210)",
        "accent-primary": "rgb(0,128,0)"
      },
      "spacing": {
        "sp-5_6": "5.6px",
        "sp-6": "6px",
        "sp-7": "7px",
        "sp-9": "9px",
        "sp-10": "10px",
        "sp-10_0002": "10.0002px",
        "sp-11_2": "11.2px",
        "sp-12": "12px",
        "sp-15": "15px",
        "sp-16_8": "16.8px",
        "sp-18": "18px",
        "sp-18_62": "18.62px",
        "sp-18_9994": "18.9994px",
        "sp-20": "20px",
        "sp-22": "22px",
        "sp-24": "24px",
        "sp-30": "30px",
        "sp-36": "36px",
        "sp-40": "40px",
        "sp-60": "60px",
        "sp-90": "90px",
        "sp-100": "100px",
        "sp-120": "120px",
        "sp-250": "250px",
        "gutter": "100px"
      },
      "borderRadius": {
        "r-8": "8px",
        "r-5_999": "5.999px",
        "r-50": "50px",
        "r-4": "4px",
        "r-10": "10px",
        "r-12": "12px",
        "r-14": "14px",
        "r-60": "60px",
        "r-15": "15px",
        "r-80": "80px",
        "control": "5.999px",
        "surface": "8px"
      },
      "boxShadow": {
        "e-01": "rgba(0, 0, 0, 0.15) 0px 4px 20px 0px",
        "elev-default": "rgba(0, 0, 0, 0.15) 0px 4px 20px 0px"
      },
      "fontFamily": {
        "ff-01": [
          "\"ABC Monument Grotesk Semi-Mono\"",
          "sans-serif"
        ],
        "ff-02": [
          "\"ABC Monument Grotesk\"",
          "sans-serif"
        ],
        "display": [
          "\"ABC Monument Grotesk\"",
          "sans-serif"
        ],
        "heading": [
          "\"ABC Monument Grotesk\"",
          "sans-serif"
        ],
        "body": [
          "\"ABC Monument Grotesk\"",
          "sans-serif"
        ],
        "label": [
          "\"ABC Monument Grotesk Semi-Mono\"",
          "sans-serif"
        ]
      },
      "fontSize": {
        "fs-12": "12px",
        "fs-14": "14px",
        "fs-14_652": "14.652px",
        "fs-16": "16px",
        "fs-18": "18px",
        "fs-22": "22px",
        "fs-28": "28px",
        "fs-44": "44px",
        "fs-54": "54px",
        "fs-72": "72px",
        "fs-80": "80px",
        "display": [
          "72px",
          {
            "lineHeight": "72px",
            "fontWeight": "400"
          }
        ],
        "heading": [
          "28px",
          {
            "lineHeight": "39.2px",
            "fontWeight": "400"
          }
        ],
        "body": [
          "18px",
          {
            "lineHeight": "25.2px",
            "fontWeight": "400"
          }
        ],
        "label": [
          "14px",
          {
            "lineHeight": "28px",
            "fontWeight": "400"
          }
        ]
      },
      "transitionDuration": {
        "d-250ms": "0.25s",
        "d-350ms": "0.35s",
        "d-1500ms": "1.5s",
        "d-500ms": "0.5s",
        "d-666ms": "0.666s",
        "d-700ms": "0.7s",
        "d-150ms": "0.15s",
        "d-100ms": "0.1s",
        "motion-default": "0.25s"
      },
      "transitionTimingFunction": {
        "ease-01": "ease",
        "ease-02": "linear",
        "ease-03": "linear(0 0%, 0.1641 3.52%, 0.311 7.18%, 0.4413 10.99%, 0.5553 14.96%, 0.6539 19.12%, 0.738 23.5%, 0.8086 28.15%, 0.8662 33.12%, 0.9078 37.92%, 0.9405 43.12%, 0.965 48.84%, 0.9821 55.28%, 0.992 61.97%, 0.9976 70.09%, 1 100%)",
        "ease-04": "cubic-bezier(0.77, 0, 0.175, 1)",
        "ease-05": "cubic-bezier(0.42, 0, 0, 1)",
        "ease-06": "steps(2, start)",
        "motion-default": "ease"
      },
      "screens": {
        "bp-820": {
          "min": "820px"
        },
        "bp-1024": {
          "min": "1024px"
        },
        "bp-1180": {
          "min": "1180px"
        },
        "bp-1280": {
          "min": "1280px"
        },
        "bp-1920": {
          "min": "1920px"
        },
        "bp-max-1919.98": {
          "max": "1919.98px"
        },
        "bp-max-1440.98": {
          "max": "1440.98px"
        },
        "bp-max-1366": {
          "max": "1366px"
        },
        "bp-max-1279.98": {
          "max": "1279.98px"
        },
        "bp-max-1179.98": {
          "max": "1179.98px"
        },
        "bp-max-932": {
          "max": "932px"
        },
        "bp-max-820": {
          "max": "820px"
        },
        "bp-max-767.98": {
          "max": "767.98px"
        }
      },
      "maxWidth": {
        "content": "1240px"
      }
    }
  },
  "plugins": []
};
