import { lazy } from "react";

// One entry per captured page. Add a page by adding its component here.
export const routes = [
  { path: "/", title: "brand.ai | AI for brand management", Page: lazy(() => import("./pages/HomePage.jsx")) },
  { path: "/security", title: "SOC 2 certified, zero training on your data | brand.ai", Page: lazy(() => import("./pages/Security.jsx")) },
  { path: "/company", title: "Tools for those who believe in brand | brand.ai", Page: lazy(() => import("./pages/Company.jsx")) },
  { path: "/careers", title: "Join toolmakers between code and craft | brand.ai", Page: lazy(() => import("./pages/Careers.jsx")) },
  { path: "/blog", title: "Insights on brand strategy and AI | brand.ai", Page: lazy(() => import("./pages/Blog.jsx")) },
  { path: "/book-a-demo", title: "Book a Personalized brand.ai Demo for Your Team | brand.ai", Page: lazy(() => import("./pages/BookADemo.jsx")) },
  { path: "/brand-os", title: "Turn brand guidelines into intelligent systems | brand.ai", Page: lazy(() => import("./pages/BrandOs.jsx")) },
  { path: "/brand-studio", title: "Where brand intelligence meets execution | brand.ai", Page: lazy(() => import("./pages/BrandStudio.jsx")) },
  { path: "/product", title: "Brand management software that preserves craft | brand.ai", Page: lazy(() => import("./pages/Product.jsx")) },
  { path: "/enterprise", title: "Enterprise brand management for global teams | brand.ai", Page: lazy(() => import("./pages/Enterprise.jsx")) },
  { path: "/teams", title: "Brand management software for growing teams | brand.ai", Page: lazy(() => import("./pages/Teams.jsx")) },
  { path: "/faq", title: "Frequently asked questions | brand.ai", Page: lazy(() => import("./pages/Faq.jsx")) },
  { path: "/legal/privacy", title: "Privacy Policy – brand.ai", Page: lazy(() => import("./pages/LegalPrivacy.jsx")) },
  { path: "/legal/acceptable-use-policy", title: "Acceptable Use Policy | brand.ai", Page: lazy(() => import("./pages/LegalAcceptableUsePolicy.jsx")) },
  { path: "/careers/senior-software-engineer", title: "Senior Software Engineer - Remote | brand.ai", Page: lazy(() => import("./pages/CareersSeniorSoftwareEngineer.jsx")) },
  { path: "/careers/forward-deployed-engineer", title: "Forward Deployed Engineer - Remote (USA) | brand.ai", Page: lazy(() => import("./pages/CareersForwardDeployedEngineer.jsx")) },
  { path: "/careers/software-engineer", title: "Software Engineer | brand.ai", Page: lazy(() => import("./pages/CareersSoftwareEngineer.jsx")) },
  { path: "/careers/digital-designer", title: "Digital Designer - Remote | brand.ai", Page: lazy(() => import("./pages/CareersDigitalDesigner.jsx")) },
  { path: "/careers/product-designer", title: "Product Designer - Remote | brand.ai", Page: lazy(() => import("./pages/CareersProductDesigner.jsx")) },
  { path: "/careers/brand-support-specialist", title: "Brand Support Specialist - Remote | brand.ai", Page: lazy(() => import("./pages/CareersBrandSupportSpecialist.jsx")) },
  { path: "/careers/brand-engineer", title: "Brand Engineer - Remote | brand.ai", Page: lazy(() => import("./pages/CareersBrandEngineer.jsx")) },
  { path: "/careers/account-executive", title: "Account Executive, Enterprise - Remote | brand.ai", Page: lazy(() => import("./pages/CareersAccountExecutive.jsx")) },
  { path: "/blog/infrastructure", title: "Infrastructure – brand.ai", Page: lazy(() => import("./pages/BlogInfrastructure.jsx")) },
  { path: "/blog/insights", title: "Insights – brand.ai", Page: lazy(() => import("./pages/BlogInsights.jsx")) },
  { path: "/blog/product", title: "Product – brand.ai", Page: lazy(() => import("./pages/BlogProduct.jsx")) },
  { path: "/blog/company", title: "Company – brand.ai", Page: lazy(() => import("./pages/BlogCompany.jsx")) },
  { path: "/blog/interviews", title: "Interviews – brand.ai", Page: lazy(() => import("./pages/BlogInterviews.jsx")) },
  { path: "/blog/post/why-katie-dreke-is-betting-on-the-human-touch", title: "Why Katie Dreke is betting on the human touch – brand.ai", Page: lazy(() => import("./pages/BlogPostWhyKatie.jsx")) },
  { path: "/blog/post/your-cmo-s-days-are-numbered", title: "Your CMO's days are numbered – brand.ai", Page: lazy(() => import("./pages/BlogPostYourCmo.jsx")) },
  { path: "/home", title: "brand.ai | AI for brand management", Page: lazy(() => import("./pages/HomePage2.jsx")) },
  { path: "/blog/post/why-most-ai-pilots-never-leave-the-lab", title: "Why most AI pilots never leave the lab – brand.ai", Page: lazy(() => import("./pages/BlogPostWhyMost.jsx")) },
  { path: "/blog/post/welcome-to-brand-ai", title: "Welcome to brand.ai, the platform we always wanted", Page: lazy(() => import("./pages/BlogPostWelcomeTo.jsx")) },
  { path: "/blog/post/brand-engineers-the-role-that-didn-t-exist-until-now", title: "Brand Engineers: The Role That Didn't Exist Until Now – brand.ai", Page: lazy(() => import("./pages/BlogPostBrandEngineers.jsx")) },
  { path: "/blog/post/how-teams-are-using-brand-ai", title: "Top brand.ai Use Cases", Page: lazy(() => import("./pages/BlogPostHowTeams.jsx")) },
  { path: "/blog/post/how-brand-engineering-is-shaping-modern-brands", title: "How brand engineering is shaping moderns brands – brand.ai", Page: lazy(() => import("./pages/BlogPostHowBrand.jsx")) },
  { path: "/blog/post/your-brand-is-more-valuable-than-you-can-measure", title: "Your brand is more valuable than you can measure – brand.ai", Page: lazy(() => import("./pages/BlogPostYourBrand.jsx")) },
  { path: "/blog/post/every-brand-needs-a-living-operating-system-not-a-pdf", title: "Every brand needs a living operating system, not a PDF – brand.ai", Page: lazy(() => import("./pages/BlogPostEveryBrand.jsx")) },
  { path: "/blog/post/brands-of-loving-grace-and-humans-who-use-ai-for-good", title: "Brands of loving grace, and humans who use AI for good – brand.ai", Page: lazy(() => import("./pages/BlogPostBrandsOf.jsx")) },
];
export const ROUTE_SET = new Set(routes.map((r) => r.path));
